export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'absolute',
      bottom: 'calc(80vh + 20px)',
      right: '20px',
      backgroundColor: 'var(--sk-paper)',
      border: '2px solid var(--sk-outline)',
      borderRadius: '16px 12px 18px 10px',
      transform: 'rotate(var(--sk-rotate))',
      boxShadow: '0 4px 16px rgba(0,0,0,0.35)',
      padding: '15px 30px',
      minWidth: '60%',
      maxWidth: '95%',
      zIndex: 10,
    },
    text: {
      color: 'var(--sk-ink)',
      fontSize: '1.5rem',
      fontFamily: 'var(--sk-font-subtitle)',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      zIndex: 2,
      padding: '8px 16px',
      borderRadius: '20px',
      fontSize: '14px',
      fontWeight: 'medium',
      color: 'var(--sk-ink)',
      backgroundColor: 'var(--sk-paper-deep)',
      border: '1.5px solid var(--sk-outline)',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
  },
};
